---
title: Tidymodels and XGBooost; a few learnings
author: ''
date: '2020-05-27'
slug: tidymodels-xgboost
categories: []
tags:
  - R
  - tidymodels
  - xgboost
  - Machine Learning
publishdate: '2020-05-27'
lastmod: '2020-05-27'
---

<script src="/rmarkdown-libs/kePrint/kePrint.js"></script>


<p>This post will look at how to fit an XGBoost model using the <code>tidymodels</code> framework rather than using the <code>XGBoost</code> package directly.</p>
<p>Tidymodels is a collection of packages that aims to standardise model creation by providing commands that can be applied across different R packages. For example, once the code is written to fit an XGBoost model a large amount of the same code could be used to fit a C5.0 algorithm.</p>
<p>I will look at a dataset which I have analysed before so I know what to expect and I can compare the <code>tidymodels</code> steps with the ones I implemented originally.</p>
<p>First let’s load the necessary packages. I’ll go through what each of the <code>tidymodels</code> packages does as we go along. We also call <code>doParallel</code> to enable parallelisation.</p>
<pre class="r"><code>require(dplyr)
require(rsample)
require(recipes)
require(parsnip)
require(tune)
require(dials)
require(workflows)
require(yardstick)
require(knitr)
require(kableExtra)
require(xgboost)
require(ggplot2)
require(data.table)

#Parallelisation
require(doParallel)
cores &lt;- parallel::detectCores(logical = FALSE)
registerDoParallel(cores = cores)</code></pre>
<p>The first step is to load in the data and apply any relevant pre-processing steps. Here I won’t focus on exploring the data, I’m more interested in following the <code>tidymodels</code> workflow. Also, I can’t talk about the details of this dataset too much for privacy reasons.</p>
<p>This dataset is already split in training and testing.</p>
<pre class="r"><code>dim(mwTrainSet)</code></pre>
<pre><code>## [1] 10000    28</code></pre>
<div id="preprocessing" class="section level3">
<h3>Preprocessing</h3>
<p>The <code>recipes</code> package can be used to handle preprocessing. You need to build a recipe object that will contain a number of different steps to be followed. This recipe can then be applied to other data, e.g. testing data or new data from the same source.</p>
<p><code>recipes</code> contains a large number of <code>step</code> functions that aim to account for any necessity you will need in your preprocessing.</p>
<pre class="r"><code>myRecipe&lt;- recipes::recipe(outcome ~ ., data=mwTrainSet) %&gt;% 
  recipes::step_mutate(os = as.factor(os)) %&gt;%
  recipes::step_mutate(ob = as.factor(ob)) %&gt;%
  step_rm(id) %&gt;%
  step_mutate(w50s = ifelse(ds&lt;=0.5,&#39;TRUE&#39;,&#39;FALSE&#39;)) %&gt;%
  prep()</code></pre>
<p>This is not my recipe in full but you can see how the process works. <code>os</code> and <code>ob</code> are logical variables and I want to convert them to factors as required by XGBoost. I’m also removing the <code>id</code> variable and creating a new variable <code>w50s</code>.</p>
<p>Here I would like to note that if the logical variables were categorical instead I could have used a step like <code>step_string2factor(all_nominal())</code> to convert them all into factors at the same time. However, at this time I’m not aware that the required <code>all_logical</code> or <code>step_logic2factor</code> exist so I mutate the variables one by one. There is an open issue with this request <a href="https://github.com/tidymodels/recipes/issues/193">here</a>.</p>
<p>You can find a list of all step functions available <a href="https://recipes.tidymodels.org/reference/">here</a>.</p>
<p>Now that the recipe is built we can use the <code>bake</code> function to actually run our data through it. I will save the modified dataset in a new object.</p>
<pre class="r"><code>proc_mwTrainSet &lt;- myRecipe %&gt;% bake(mwTrainSet)</code></pre>
</div>
<div id="cross-validation" class="section level3">
<h3>Cross-validation</h3>
<p>Moving along the model-building pipeline we want to create some cross-validation folds from our training set. We will use these folds during the tuning process. For this purpose I use the <code>vfold_cv</code> function from <code>rsample</code> which in my case creates 5 folds of the processed data with each fold split with an 80/20 ratio. I also set the seed for reproducibility.</p>
<pre class="r"><code>set.seed(2020)
cvFolds &lt;- mwTrainSet %&gt;% 
  bake(myRecipe, new_data = .) %&gt;%
  rsample::vfold_cv(v = 5)

cvFolds</code></pre>
<pre><code>## #  5-fold cross-validation 
## # A tibble: 5 x 2
##   splits          id   
##   &lt;named list&gt;    &lt;chr&gt;
## 1 &lt;split [8K/2K]&gt; Fold1
## 2 &lt;split [8K/2K]&gt; Fold2
## 3 &lt;split [8K/2K]&gt; Fold3
## 4 &lt;split [8K/2K]&gt; Fold4
## 5 &lt;split [8K/2K]&gt; Fold5</code></pre>
</div>
<div id="model-specification" class="section level3">
<h3>Model specification</h3>
<p>We have a processed dataset and we know how we want to validate it so we can now specify the model we want to fit to the data.</p>
<pre class="r"><code>xgmodel&lt;-parsnip::boost_tree(
  mode = &quot;classification&quot;,
  trees = 1000, #nrounds
  learn_rate = tune(), #eta
  sample_size = tune(), #subsample
  mtry = tune(), #colsample_bytree
  min_n = tune(), #min_child_weight
  tree_depth = tune() #max_depth
) %&gt;%
  set_engine(&quot;xgboost&quot;, objective = &quot;multi:softprob&quot;,
             lambda=0, alpha=1, num_class=3,verbose=1)

xgmodel</code></pre>
<pre><code>## Boosted Tree Model Specification (classification)
## 
## Main Arguments:
##   mtry = tune()
##   trees = 1000
##   min_n = tune()
##   tree_depth = tune()
##   learn_rate = tune()
##   sample_size = tune()
## 
## Engine-Specific Arguments:
##   objective = multi:softprob
##   lambda = 0
##   alpha = 1
##   num_class = 3
##   verbose = 1
## 
## Computational engine: xgboost</code></pre>
<p>The <code>parsnip</code> package provides an interface for many types of models and the different types of packages that fall into those types. For example, because XGBoost is a boosted tree type of model we use the <code>boost_tree</code> function.</p>
<p><code>boost_tree</code> provides general parameters that can be used on other boosted tree models. In my specification below I included the XGBoost translation of the <code>boost_tree</code> names.</p>
<p>Many of the parameters have a <code>tune()</code> value assigned to them. This is because later we are going to construct a parameter grid with which we will be able to search what the best parameters are.</p>
<p>Also note that <code>set_engine</code> is where we set that we are using XGBoost and that we can pass XGBoost specific options into this function as well.</p>
<p>By using <code>parsnip</code> you avoid many of the pecularities that XGBoost has. If you used XGBoost directly you would find that you need to encode categorical variables as dummies, you also need to use the specific XGBoost format for matrices <code>xgb.DMatrix</code> and you need to separate out the labels from the predictors.</p>
<p>Here I didn’t need to do any of that because <code>parsnip</code> handles those requirements internally. I think the <code>tidymodels</code> framework makes your life easier but it’s wise to still know how the underlying engines work if you are going to use them.</p>
</div>
<div id="tuning-the-model" class="section level3">
<h3>Tuning the model</h3>
<p>We now turn to the <code>dials</code> package. To me this is where <code>tiymodels</code> provides its biggest benefits. It gives the user the ability to tune models in a reproducible manner that is easy to replicate.</p>
<p>First, we need to set up a <code>parameters</code> object with the parameters we want to be tuned.</p>
<pre class="r"><code>xgboostParams &lt;- dials::parameters(
  min_n(),
  tree_depth(),
  learn_rate(),
  finalize(mtry(),select(proc_mwTrainSet,-outcome)),
  sample_size = sample_prop(c(0.4, 0.9))
)</code></pre>
<p>Note that, <code>mtry</code> had to be treated differently and we had to ‘finalize’ it. The reason being that for parameters whose range depends on the data set the user has to provide the range. As <code>mtry()</code> is the number of variables used in the making of each tree we need to bound it by the number of variables available.</p>
<pre class="r"><code>mtry()</code></pre>
<pre><code>## # Randomly Selected Predictors  (quantitative)
## Range: [1, ?]</code></pre>
<pre class="r"><code>finalize(mtry(),select(proc_mwTrainSet,-outcome))</code></pre>
<pre><code>## # Randomly Selected Predictors  (quantitative)
## Range: [1, 49]</code></pre>
<p>Another quirk we encounter here is that <code>boost_tree</code> takes the parameter <code>sample_size</code> as integer but XGBoost requires this parameter as a proportion, hence we use <code>sample_prop</code> to specify the range.</p>
<p>Once the parameters to be tuned are defined we can use the <code>grid_max_entropy</code> function to create the grid that will be explored. The max entropy grid is defined like so in the documentation:</p>
<blockquote>
<p>Experimental designs for computer experiments are used to construct parameter grids that try to cover the parameter space such that any portion of the space has an observed combination that is not too far from it.</p>
</blockquote>
<p>So, we are letting <code>dials</code> define a grid for us that will explore as much as the parameter space as possible. I will set the number of combinations to 100.</p>
<pre class="r"><code>set.seed(2020)
xgGrid &lt;- dials::grid_max_entropy(xgboostParams, size = 100)

#knitr::kable(head(xgGrid))
kablify(xgGrid[1:5,])</code></pre>
<table class="table table-striped" style="margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:right;">
min_n
</th>
<th style="text-align:right;">
tree_depth
</th>
<th style="text-align:right;">
learn_rate
</th>
<th style="text-align:right;">
mtry
</th>
<th style="text-align:right;">
sample_size
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;">
40
</td>
<td style="text-align:right;">
8
</td>
<td style="text-align:right;">
0.0017557
</td>
<td style="text-align:right;">
22
</td>
<td style="text-align:right;">
0.4202777
</td>
</tr>
<tr>
<td style="text-align:right;">
12
</td>
<td style="text-align:right;">
9
</td>
<td style="text-align:right;">
0.0000007
</td>
<td style="text-align:right;">
9
</td>
<td style="text-align:right;">
0.8233843
</td>
</tr>
<tr>
<td style="text-align:right;">
22
</td>
<td style="text-align:right;">
14
</td>
<td style="text-align:right;">
0.0000141
</td>
<td style="text-align:right;">
24
</td>
<td style="text-align:right;">
0.6387196
</td>
</tr>
<tr>
<td style="text-align:right;">
31
</td>
<td style="text-align:right;">
8
</td>
<td style="text-align:right;">
0.0000006
</td>
<td style="text-align:right;">
16
</td>
<td style="text-align:right;">
0.8828089
</td>
</tr>
<tr>
<td style="text-align:right;">
32
</td>
<td style="text-align:right;">
6
</td>
<td style="text-align:right;">
0.0001357
</td>
<td style="text-align:right;">
41
</td>
<td style="text-align:right;">
0.7991674
</td>
</tr>
</tbody>
</table>
<p>This is great. When I first fit this model I was using a custom built function for tuning that I found on stackoverflow.</p>
<pre class="r"><code>set.seed(1234)
searchGridSubCol &lt;- expand.grid(min_child_weight=c(2),
                                subsample = c(0.75,0.6,0.9), 
                                colsample_bytree = c(0.6,0.8),
                                lam = c(2),
                                alph=c(0),
                                depth=c(6,10,3),
                                etaa=c(0.009,0.011,0.013,0.014)
                                )
ntrees &lt;- 5000
mllHyperparameters &lt;- apply(searchGridSubCol, 1, function(parameterList){
  
  #Extract Parameters to test
  currentSubsampleRate &lt;- parameterList[[&quot;subsample&quot;]]
  currentColsampleRate &lt;- parameterList[[&quot;colsample_bytree&quot;]]
  currentMCW &lt;- parameterList[[&quot;min_child_weight&quot;]]
  currentLambda &lt;- parameterList[[&quot;lam&quot;]]
  currentAlpha &lt;- parameterList[[&quot;alph&quot;]]
  currentDepth &lt;- parameterList[[&quot;depth&quot;]]
  currentEta &lt;- parameterList[[&quot;etaa&quot;]]
  
  xgb_params &lt;- list(&quot;objective&quot; = &quot;multi:softprob&quot;,
                     &quot;eval_metric&quot; = &quot;mlogloss&quot;,
                     &quot;num_class&quot; = 3,
                     &quot;eta&quot; = currentEta,
                     subsample = currentSubsampleRate,
                     colsample_bytree= currentColsampleRate,
                     min_child_weight=currentMCW,
                     lambda=currentLambda,
                     alpha=currentAlpha,
                     max_depth=currentDepth)
})</code></pre>
<p>I did quite an extensive search but I always chose values in incremental steps, e.g., for <code>eta</code> I would try 0.1,0.15,0.2,… Using <code>dials</code> you might get to combinations that you didn’t think about but mostly it’ll optimise how to set the parameter combinations given the size parameter.</p>
<p>Next, we create a workflow from <code>workflows</code> that we will pass into the tuning object in the following step. We specify the formula for the model we want to fit based on the dependent variable <code>outcome</code>.</p>
<pre class="r"><code>xgWorkflow &lt;- 
  workflows::workflow() %&gt;%
  add_model(xgmodel) %&gt;% 
  add_formula(outcome ~ .)</code></pre>
<p>We can finally tune the model! We pass the workflow, cross-validation folds, grid of parameters to test and the metric we want to save from each model output. Note that <code>metric_set</code> comes from the <code>yardstick</code> package.</p>
<pre class="r"><code>xgTuned &lt;- tune_grid(
  object = xgWorkflow,
  resamples = cvFolds,
  grid      = xgGrid,
  metrics   = metric_set(mn_log_loss),
  control   = control_grid(verbose = TRUE))</code></pre>
<p>Tuning the model on that grid took a while, around 90 minutes in a 8-core machine runing in parallel.</p>
<p>Since we are running parallelised code there is no progress output shown even though verbose is set to True.</p>
<p>Also, note that I set the <code>trees</code> parameter to 1000 in the model specification. This means that we are fitting 100 different XGBoost model and each one of those will build 1000 trees. XGBoost supports early stopping, i.e., you can specify a parameter that tells the model to stop if there has been no log-loss improvement in the last <code>N</code> trees.</p>
<p>Setting an early stopping criterion can save computation time. If there’s a parameter combination that is not performing well the model will stop well before reaching the 1000th tree.</p>
<p>Early stopping is currently not supported in the <code>boost_tree</code> function. However, according to this <a href="https://github.com/topepo/caret/issues/641">post</a> it has been very recently implemented in the development version so you could give it a try if you were so inclined.</p>
<p>The <code>xgTuned</code> object contains the 100 combinations of parameters we tested and the corresponding mean log-loss from the cross-validation.</p>
<p>The <code>show_best</code> function outputs the best performing combinations.</p>
<pre class="r"><code>xgTuned %&gt;% tune::show_best(metric = &quot;mn_log_loss&quot;) %&gt;% kablify()</code></pre>
<table class="table table-striped" style="margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:right;">
mtry
</th>
<th style="text-align:right;">
min_n
</th>
<th style="text-align:right;">
tree_depth
</th>
<th style="text-align:right;">
learn_rate
</th>
<th style="text-align:right;">
sample_size
</th>
<th style="text-align:left;">
.metric
</th>
<th style="text-align:left;">
.estimator
</th>
<th style="text-align:right;">
mean
</th>
<th style="text-align:right;">
n
</th>
<th style="text-align:right;">
std_err
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;">
19
</td>
<td style="text-align:right;">
8
</td>
<td style="text-align:right;">
6
</td>
<td style="text-align:right;">
0.0086232
</td>
<td style="text-align:right;">
0.8386232
</td>
<td style="text-align:left;">
mn_log_loss
</td>
<td style="text-align:left;">
multiclass
</td>
<td style="text-align:right;">
0.3126151
</td>
<td style="text-align:right;">
5
</td>
<td style="text-align:right;">
0.0056380
</td>
</tr>
<tr>
<td style="text-align:right;">
16
</td>
<td style="text-align:right;">
9
</td>
<td style="text-align:right;">
14
</td>
<td style="text-align:right;">
0.0153090
</td>
<td style="text-align:right;">
0.7279057
</td>
<td style="text-align:left;">
mn_log_loss
</td>
<td style="text-align:left;">
multiclass
</td>
<td style="text-align:right;">
0.3130304
</td>
<td style="text-align:right;">
5
</td>
<td style="text-align:right;">
0.0073298
</td>
</tr>
<tr>
<td style="text-align:right;">
42
</td>
<td style="text-align:right;">
19
</td>
<td style="text-align:right;">
12
</td>
<td style="text-align:right;">
0.0148805
</td>
<td style="text-align:right;">
0.7756686
</td>
<td style="text-align:left;">
mn_log_loss
</td>
<td style="text-align:left;">
multiclass
</td>
<td style="text-align:right;">
0.3147089
</td>
<td style="text-align:right;">
5
</td>
<td style="text-align:right;">
0.0067372
</td>
</tr>
<tr>
<td style="text-align:right;">
16
</td>
<td style="text-align:right;">
17
</td>
<td style="text-align:right;">
4
</td>
<td style="text-align:right;">
0.0147389
</td>
<td style="text-align:right;">
0.5218267
</td>
<td style="text-align:left;">
mn_log_loss
</td>
<td style="text-align:left;">
multiclass
</td>
<td style="text-align:right;">
0.3196296
</td>
<td style="text-align:right;">
5
</td>
<td style="text-align:right;">
0.0051067
</td>
</tr>
<tr>
<td style="text-align:right;">
39
</td>
<td style="text-align:right;">
26
</td>
<td style="text-align:right;">
9
</td>
<td style="text-align:right;">
0.0178508
</td>
<td style="text-align:right;">
0.4542553
</td>
<td style="text-align:left;">
mn_log_loss
</td>
<td style="text-align:left;">
multiclass
</td>
<td style="text-align:right;">
0.3210408
</td>
<td style="text-align:right;">
5
</td>
<td style="text-align:right;">
0.0061055
</td>
</tr>
</tbody>
</table>
<p>We can also get all the combinations with <code>collect_metrics</code> and we can plot them against mean log-loss.</p>
<pre class="r"><code>xgTuned %&gt;% collect_metrics() %&gt;% 
  select(mean,mtry:sample_size) %&gt;% data.table %&gt;% 
  melt(id=&quot;mean&quot;) %&gt;% 
  ggplot(aes(y=mean,x=value,colour=variable)) + 
  geom_point(show.legend = FALSE) + 
  facet_wrap(variable~. , scales=&quot;free&quot;) + theme_bw() +
  labs(y=&quot;Mean log-loss&quot;, x = &quot;Parameter&quot;)</code></pre>
<p><img src="/post/2020-05-24-tidymodels-and-xgbooost-a-few-learnings_files/figure-html/unnamed-chunk-19-1.png" width="672" /></p>
<p>No clear patterns emerge from looking at the plots except that very small learn rate values lead to high log-loss. Having a grid that covers the parameter space as extensively as possible leads to many combinations that aren’t so great but the important point is that we get also get the ones that perform very well.</p>
</div>
<div id="fitting-the-best-model" class="section level3">
<h3>Fitting the best model</h3>
<p>We can pick the best combination of parameters with <code>select_best</code>.</p>
<pre class="r"><code>xgBestParams &lt;- xgTuned %&gt;% select_best(&quot;mn_log_loss&quot;)</code></pre>
<p>The model is then finalised with those parameters with <code>finalize_model</code> and then the training data can be fit to it using <code>fit</code></p>
<pre class="r"><code>xgboost_model_final &lt;- xgmodel %&gt;% finalize_model(xgBestParams)
xgTrainFit&lt;-xgboost_model_final %&gt;% fit(outcome~., data=proc_mwTrainSet)
xgTrainFit</code></pre>
<pre><code>## parsnip model object
## 
## Fit time:  1m 2.2s 
## ##### xgb.Booster
## raw: 7.5 Mb 
## call:
##   xgboost::xgb.train(params = list(eta = 0.00862323672548215, max_depth = 6L, 
##     gamma = 0, colsample_bytree = 0.358490566037736, min_child_weight = 8L, 
##     subsample = 0.838623173511587), data = x, nrounds = 1000, 
##     verbose = 1, objective = &quot;multi:softprob&quot;, num_class = 3L, 
##     lambda = 0, alpha = 1, nthread = 1)
## params (as set within xgb.train):
##   eta = &quot;0.00862323672548215&quot;, max_depth = &quot;6&quot;, gamma = &quot;0&quot;, colsample_bytree = &quot;0.358490566037736&quot;, min_child_weight = &quot;8&quot;, subsample = &quot;0.838623173511587&quot;, objective = &quot;multi:softprob&quot;, num_class = &quot;3&quot;, lambda = &quot;0&quot;, alpha = &quot;1&quot;, nthread = &quot;1&quot;, silent = &quot;1&quot;
## xgb.attributes:
##   niter
## callbacks:
##   cb.print.evaluation(period = print_every_n)
## # of features: 53 
## niter: 1000
## nfeatures : 53</code></pre>
<p>We can also get predictions on the training set; <code>predict</code> outputs the predicted classes while <code>predict_classprob.model_fit</code> outputs the class probabilities for each of the 3 classes.</p>
<pre class="r"><code>xgTrainPreds&lt;- xgTrainFit %&gt;% predict(new_data=proc_mwTrainSet)
xgTrainPredProbs &lt;- xgTrainFit %&gt;% predict_classprob.model_fit(new_data=proc_mwTrainSet)
proc_mwTrainSet &lt;- bind_cols(proc_mwTrainSet,xgTrainPreds,xgTrainPredProbs)</code></pre>
<p>In the table below <code>outcome</code> is the dependent variable, <code>.pred_class</code> the predicted class and <code>Type*</code> are the class probabilities. As an example, in the first row Type2 has the highest probability so the prediction is assingnd to this class.</p>
<pre class="r"><code>proc_mwTrainSet %&gt;% select(Type1:outcome) %&gt;% head %&gt;% kablify()</code></pre>
<table class="table table-striped" style="margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:right;">
Type1
</th>
<th style="text-align:right;">
Type2
</th>
<th style="text-align:right;">
Type3
</th>
<th style="text-align:left;">
.pred_class
</th>
<th style="text-align:left;">
outcome
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;">
0.0591691
</td>
<td style="text-align:right;">
0.9169078
</td>
<td style="text-align:right;">
0.0239230
</td>
<td style="text-align:left;">
Type2
</td>
<td style="text-align:left;">
Type2
</td>
</tr>
<tr>
<td style="text-align:right;">
0.4554967
</td>
<td style="text-align:right;">
0.5316201
</td>
<td style="text-align:right;">
0.0128832
</td>
<td style="text-align:left;">
Type2
</td>
<td style="text-align:left;">
Type1
</td>
</tr>
<tr>
<td style="text-align:right;">
0.9568088
</td>
<td style="text-align:right;">
0.0382318
</td>
<td style="text-align:right;">
0.0049593
</td>
<td style="text-align:left;">
Type1
</td>
<td style="text-align:left;">
Type1
</td>
</tr>
<tr>
<td style="text-align:right;">
0.0451100
</td>
<td style="text-align:right;">
0.9463689
</td>
<td style="text-align:right;">
0.0085212
</td>
<td style="text-align:left;">
Type2
</td>
<td style="text-align:left;">
Type2
</td>
</tr>
<tr>
<td style="text-align:right;">
0.0335070
</td>
<td style="text-align:right;">
0.0201417
</td>
<td style="text-align:right;">
0.9463512
</td>
<td style="text-align:left;">
Type3
</td>
<td style="text-align:left;">
Type3
</td>
</tr>
<tr>
<td style="text-align:right;">
0.0105972
</td>
<td style="text-align:right;">
0.9814348
</td>
<td style="text-align:right;">
0.0079681
</td>
<td style="text-align:left;">
Type2
</td>
<td style="text-align:left;">
Type2
</td>
</tr>
</tbody>
</table>
</div>
<div id="model-evaluation" class="section level3">
<h3>Model evaluation</h3>
<p>We can evaluate the model using the <code>yardstick</code> package. The <code>metrics</code> function takes parameters <code>truth</code> and <code>estimate</code> and will output the accuracy and kappa metrics. If you pass the class probabilities it also calculates mean log-loss and roc_auc.</p>
<pre class="r"><code>proc_mwTrainSet %&gt;% yardstick::metrics(truth=outcome,estimate=.pred_class,Type1,Type2,Type3) %&gt;% kablify()</code></pre>
<table class="table table-striped" style="margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:left;">
.metric
</th>
<th style="text-align:left;">
.estimator
</th>
<th style="text-align:right;">
.estimate
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
accuracy
</td>
<td style="text-align:left;">
multiclass
</td>
<td style="text-align:right;">
0.9432000
</td>
</tr>
<tr>
<td style="text-align:left;">
kap
</td>
<td style="text-align:left;">
multiclass
</td>
<td style="text-align:right;">
0.9116029
</td>
</tr>
<tr>
<td style="text-align:left;">
mn_log_loss
</td>
<td style="text-align:left;">
multiclass
</td>
<td style="text-align:right;">
0.1906783
</td>
</tr>
<tr>
<td style="text-align:left;">
roc_auc
</td>
<td style="text-align:left;">
hand_till
</td>
<td style="text-align:right;">
0.9914153
</td>
</tr>
</tbody>
</table>
<p>When I first fit this model with XGBoost I got an accuracy of 0.96 and a validation log-loss of 0.306. So far with the current approach accuracy is at 0.943 and validation log-loss (from the <code>xgTuned</code> table in the previous section) at 0.313. I haven’t achieved results as good as I had before but I also have to note that getting to those values took me a lot of effort and going through the tuning process many times. Here, I did one pass and I’m already close. If I expand the tuning grid I could probably get better performance metrics.</p>
<p>We can also get the confusion matrix with <code>conf_mat</code>.</p>
<pre class="r"><code>cm&lt;-proc_mwTrainSet %&gt;% yardstick::conf_mat(truth=outcome,estimate=.pred_class) 
autoplot(cm, type = &quot;heatmap&quot;) </code></pre>
<p><img src="/post/2020-05-24-tidymodels-and-xgbooost-a-few-learnings_files/figure-html/unnamed-chunk-26-1.png" width="672" /></p>
<p>We can see that the <code>Type3</code> class is better predicted than the other two.</p>
<p>In order to <em>really</em> finalise the model I would need to fit the test data and check the metrics in that set which has not been used in the modeling and hence provides an unbiased validation of out approach. I’m not going to focus on that here mainly because the test set did not come with labels so I won’t be able to calculate any performance metrics from it.</p>
<p>If this was a real life case, once you were happy with the results in the test set you could put the model into production and make predictions on new data.</p>
</div>
<div id="conclusions" class="section level3">
<h3>Conclusions</h3>
<p>This was a really quick tour around how <code>tidymodels</code> works. I think it has many advantages and it definitively makes the task of fitting reproducible ML models faster and more user-friendly so it is certainly something I will keep playing with.</p>
<p>I still think familiarity with the underlying models, in this case XGBoost, helps the user understand what this framework can and can’t do so I wouldn’t use it blindly without having some experience with the original model first.</p>
</div>
